apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: mail-pass
  namespace: monitoring
  labels:
    release: monitoring
data:
  gmail-pass: <<tluf rfwl ifxl etiv,ENTER_YOUR_APP PASSWORDS_IN_BASE64_ENCODED_FORMAT>>


